version: '3'
services:
  jekyllbuild:
    build:
      context: .
      args:
        build_command: "jekyll build"
    volumes:
      - .:/srv/jekyll
  nginx:
    image: nginx
    volumes:
      - ./_site:/var/www/jekyll
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "29200:29200"
